### ISSUE TITLE
build_graphs `os.walk` not working

### ISSUE THREAD

**Issue by duncster94** [berc-uoft/Transformer-GCN-QA#14]
On my Windows machine this line doesn't execute:

https://github.com/berc-uoft/Transformer-GCN-QA/blob/e34d75389c13284edd57e96edfe63c92c02f245a/src/cli/build_graphs.py#L25

Haven't tested it on Linux. @JohnGiorgi any ideas?

**Comment by JohnGiorgi** [comment]
It works on MacOS and presumably Linux. Must be a windows thing.

Let’s find a OS agnostic way to loop over all subdirectories in a directory (I thought this was it).

`input_directory` will contain a subdirectory for each partition, e.g. `train`, `dev`.

**Comment by JohnGiorgi** [comment]
This was an issue with a Linux terminal being on Windows. Switched from `os.walk` to `glob` anyways (cleaner code and apparently its faster).
