### ISSUE TITLE
Detailed introduction for this repository

### ISSUE THREAD

**Issue by Jiakui** [berc-uoft/Transformer-GCN-QA#36]
Hi 

I am very interested in this awesome repository. Can you provide a detailed introduction for the code? Just about how the code works, the architecture of the neural network, and the accuracy or F1 for the test set.

Thanks

**Comment by JohnGiorgi** [comment]
Hi @Jiakui,

Thanks for the kind words. Right now this is really a work in progress, so things are a little broken and performance isn't great. If you hang on a few weeks things should get cleaned up and better documented.

That being said, to answer your questions:

> Can you provide a detailed introduction for the code?

The readme has pretty detailed instructions for [installation](https://github.com/berc-uoft/Transformer-GCN-QA#installation) and [preprocessing the data](https://github.com/berc-uoft/Transformer-GCN-QA#usage). Were you stuck on something in particular?

> the architecture of the neural network

Check out the [models.py](https://github.com/berc-uoft/Transformer-GCN-QA/blob/master/src/models.py) file, it contains the architecture. It should be easy enough to read it off from there.

> and the accuracy or F1 for the test set

Again, not very good currently. We are working out some bugs. We can get ~44% on MedHop and 50+% on WikiHop.

**Comment by Frankey419** [comment]
Hi

I am very interested in your work, I wonder if it's convenient for you providing a paper or figure things for the description? 

Thanks

**Comment by Frankey419** [comment]
By the way, is the task your model handles selecting an answer from the candidates? As described in model.py file.

**Comment by JohnGiorgi** [comment]
@cococold Hi!

We haven’t published this work as it is still in progress, but it is most heavily inspired by [this](https://arxiv.org/abs/1808.09920) paper!

Yes, given a query, and a set of documents, our model tries to select the answer to the query from a list of candidate answers. You can check out [this](https://transacl.org/ojs/index.php/tacl/article/viewFile/1325/299) paper for more info on the task.

**Comment by Frankey419** [comment]
> @cococold Hi!
> 
> We haven’t published this work as it is still in progress, but it is most heavily inspired by [this](https://arxiv.org/abs/1808.09920) paper!
> 
> Yes, given a query, and a set of documents, our model tries to select the answer to the query from a list of candidate answers. You can check out [this](https://transacl.org/ojs/index.php/tacl/article/viewFile/1325/299) paper for more info on the task.

thanks for your replay, I'd like to follow your job😊
