### ISSUE TITLE
The coreference list is empty.

### ISSUE THREAD

**Issue by FayeXXX** [berc-uoft/Transformer-GCN-QA#40]
Hi,
Thank u sooo much for sharing this. And I ran the preprocess part for several hours and found that there was no coreference extracted. I wonder if it was caused by
 '''NEURALCOREF_GREEDYNESS = 0.10'''
(in constrains.py). 
And by the way, how does this part contributes to the whole performance?  Can co-occurrence phrase alone work well on this task?

**Comment by JohnGiorgi** [comment]
Hi!

Thanks for your interest in the project. Unfortunately we dropped this project some time ago. We weren’t convinced our use of graphs was a natural way to represent candidates and performance was below some simpler baselines.

I think I will likely archive the repo to prevent any confusion in the future.
